apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: kubernetes-cluster-abhishekkashyap
  labels:
    app: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: kashyapabhishek123/biannual:1
          ports:
            - protocol: TCP
              name: http
              containerPort: 8080
              
              
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: kubernetes-cluster-abhishekkashyap
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30157
  

     