apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: kubernetes-cluster-abhishekkashyap
  labels:
    app: java-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: kashyapabhishek123/c-abhishekkashyap-master:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
              
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: kubernetes-cluster-abhishekkashyap
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
  - protocol: TCP
    nodePort: 30157
    port: 8080
    targetPort: 8080
  
 
    
     
